name: Spell check .md files
on: push

jobs:
  build:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@v0
      with:
        source_files: 'en-US/*.md'
        task_name: Markdown
